# Загрузка датасета и импорты

In [8]:
import kagglehub

path = kagglehub.dataset_download("taeefnajib/used-car-price-prediction-dataset")

In [9]:
import pandas as pd
from IPython import display

In [ ]:
df = pd.read_csv(path+"/used_cars.csv")

# EDA

## Знакомство с данными

In [14]:
print(df.shape)

(4009, 12)

In [20]:
display(df.head())

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"

In [22]:
display(df.sample(5))

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
2343,Tesla,Model 3 Long Range,2018,"43,000 mi.",NaN,271.0HP Electric Motor Electric Fuel System,1-Speed A/T,Red,Black,At least 1 accident or damage reported,Yes,"$30,499"
1478,Kia,Sorento LX,2021,"54,200 mi.",Gasoline,191.0HP 2.5L 4 Cylinder Engine Gasoline Fuel,A/T,White,Black,None reported,Yes,"$23,800"
855,Ford,Bronco,1974,"6,217 mi.",–,–,–,Dark Gray Metallic,–,None reported,Yes,"$115,000"
299,Porsche,718 Cayman S,2019,"9,500 mi.",Gasoline,350.0HP 2.5L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Red,Black,At least 1 accident or damage reported,Yes,"$69,000"
390,Volkswagen,Arteon 2.0T SE,2021,"13,613 mi.",Gasoline,2.0 Liter TSI,Automatic,Pure White,Titan Black,None reported,NaN,"$29,798"

In [25]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 4009 entries, 0 to 4008
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         4009 non-null   str
 1   model         4009 non-null   str
 2   model_year    4009 non-null   int64
 3   milage        4009 non-null   str
 4   fuel_type     3839 non-null   str
 5   engine        4009 non-null   str
 6   transmission  4009 non-null   str
 7   ext_col       4009 non-null   str
 8   int_col       4009 non-null   str
 9   accident      3896 non-null   str
 10  clean_title   3413 non-null   str
 11  price         4009 non-null   str
dtypes: int64(1), str(11)
memory usage: 892.6 KB
None

In [27]:
print(df.describe(include='all'))

       brand    model   model_year       milage fuel_type  \
count   4009     4009  4009.000000         4009      3839
unique    57     1898          NaN         2818         7
top     Ford  M3 Base          NaN  110,000 mi.  Gasoline
freq     386       30          NaN           16      3309
mean     NaN      NaN  2015.515590          NaN       NaN
std      NaN      NaN     6.104816          NaN       NaN
min      NaN      NaN  1974.000000          NaN       NaN
25%      NaN      NaN  2012.000000          NaN       NaN
50%      NaN      NaN  2017.000000          NaN       NaN
75%      NaN      NaN  2020.000000          NaN       NaN
max      NaN      NaN  2024.000000          NaN       NaN

                            engine transmission ext_col int_col  \
count                         4009         4009    4009    4009
unique                        1146           62     319     156
top     2.0L I4 16V GDI DOHC Turbo          A/T   Black   Black
freq                            52         1037     905    2025
mean                           NaN          NaN     NaN     NaN
std                            NaN          NaN     NaN     NaN
min                            NaN          NaN     NaN     NaN
25%                            NaN          NaN     NaN     NaN
50%                            NaN          NaN     NaN     NaN
75%                            NaN          NaN     NaN     NaN
max                            NaN          NaN     NaN     NaN

             accident clean_title    price
count            3896        3413     4009
unique              2           1     1569
top     None reported         Yes  $15,000
freq             2910        3413       39
mean              NaN         NaN      NaN
std               NaN         NaN      NaN
min               NaN         NaN      NaN
25%               NaN         NaN      NaN
50%               NaN         NaN      NaN
75%               NaN         NaN      NaN
max               NaN         NaN      NaN

In [58]:
data_info = pd.DataFrame(columns=['Признак', 'Тип', 'Пропуски', 'Уникальные значения'])

data_info.loc[len(data_info)]=['brand', 'категориальный', df['brand'].isna().sum(), df['brand'].unique().size]

data_info.loc[len(data_info)] = ['model', 'категориальный', df['model'].isna().sum(), df['model'].unique().size]

data_info.loc[len(data_info)] = ['model_year', 'порядковый', df['model_year'].isna().sum(), df['model_year'].unique().size]

data_info.loc[len(data_info)] = ['milage', 'числовой', df['milage'].isna().sum(), df['milage'].unique().size]

data_info.loc[len(data_info)] = ['fuel_type', 'категориальный', df['fuel_type'].isna().sum(), df['fuel_type'].unique().size]

data_info.loc[len(data_info)] = ['engine', 'составной', df['engine'].isna().sum(), df['engine'].unique().size]

data_info.loc[len(data_info)] = ['transmission', 'составной', df['transmission'].isna().sum(), df['transmission'].unique().size]

data_info.loc[len(data_info)] = ['ext_col', 'категориальный', df['ext_col'].isna().sum(), df['ext_col'].unique().size]

data_info.loc[len(data_info)] = ['int_col', 'категориальный', df['int_col'].isna().sum(), df['int_col'].unique().size]

data_info.loc[len(data_info)] = ['accident', 'категориальный бинарный', df['accident'].isna().sum(), df['accident'].unique().size]

data_info.loc[len(data_info)] = ['clean_title', 'категориальный бинарный', df['clean_title'].isna().sum(), df['clean_title'].unique().size]

data_info.loc[len(data_info)] = ['price', 'числовая целевая', df['price'].isna().sum(), df['price'].unique().size]

In [59]:
data_info.head(12)

         Признак                      Тип  Пропуски  Уникальные значения
0          brand           категориальный         0                   57
1          model           категориальный         0                 1898
2     model_year               порядковый         0                   34
3         milage                 числовой         0                 2818
4      fuel_type           категориальный       170                    8
5         engine                составной         0                 1146
6   transmission                составной         0                   62
7        ext_col           категориальный         0                  319
8        int_col           категориальный         0                  156
9       accident  категориальный бинарный       113                    3
10   clean_title  категориальный бинарный       596                    2
11         price         числовая целевая         0                 1569

Замечаем, что есть составные признаки, которые можно разделить на несколько более элементарных признаков

## Обработка пропущенных значений